spring:
  application:
    name: DonAlfonso
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=DonAlfonsoDB;encrypt=false;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:Dracobo2026!}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

server:
  port: ${PORT} #Valor por defecto si PORT no está configurado
  url: ${SERVER_URL} #Valor por defecto si SERVER_URL no esta configurado

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false
springdoc:
  api-docs:
    enable: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html