# docker-compose -f docker-compose-db.yml up -d
# docker-compose -f docker-compose-db.yml down
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    restart: unless-stopped
    environment:
      SA_PASSWORD: "Admin12345*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  sqlserver_data: