# docker compose -f docker-compose-luis/docker-compose-be.yml up -d --build
# docker compose -f docker-compose-luis/docker-compose-be.yml down
version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile-luis/Dockerfile
    image: luis280707/springboot-sqlserver:1.0
    container_name: springboot-sqlserver
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sql-server:1433;databaseName=losQueensAgroDB;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=losQueens123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
    networks:
      - my-network

# CONSUMIR UNA RED EXISTENTE CREADA POR OTRO COMPOSE
networks:
  my-network:
    external: true

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA
#networks:
#  my-network:
#    name: my-network  # red compartida, visible desde ambos compose
#    driver: bridge
