# docker compose -f docker-compose-aynara/docker-compose-db.yml up -d --build
# docker compose -f docker-compose-aynara/docker-compose-db.yml down

version: '3'

services:
  sqlserver:
    image: aynaranolazco/sql-server:2022
    container_name: sql-server
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "losQueens123!"

      MSSQL_PID: "Express"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  sql_data: