name: Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Build Docker Image and Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar el motor de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Iniciar sesión en DockerHub usando tus secretos personalizados
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_AYNARA }}
          password: ${{ secrets.DOCKERHUB_TOKEN_AYNARA }}

      # 4. Construir la imagen usando la ruta del entregable (dockerfile-juan/Dockerfile)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile-juan/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME_AYNARA }}/pipeline-t03-be:latest
            ${{ secrets.DOCKERHUB_USERNAME_AYNARA }}/pipeline-t03-be:${{ github.sha }}